/**
 * Sample Industrial Machines Dataset
 */

const sampleMachines = [
  {
    machineId: 'MCH-101',
    name: 'CNC Milling Center Alpha',
    plant: 'Plant Alpha',
    location: 'Plant A - Cell 01',
    department: 'Precision Machining',
    status: 'Healthy',
    runningHours: 1420,
    healthScore: 98,
    temperature: 42.5,
    vibration: 1.45,
    vibrationX: 1.2,
    vibrationY: 1.1,
    vibrationZ: 1.4,
    pressure: 4.8,
    voltage: 415,
    current: 12.4,
    rpm: 1750,
    power: 5.8,
    humidity: 45,
    sensorId: 'SN-SENS-8891',
    operator: 'Marcus Vance',
    lastMaintenance: '2026-06-15',
    nextMaintenance: '2026-09-15',
  },
  {
    machineId: 'MCH-102',
    name: 'High-Pressure Hydraulic Press',
    plant: 'Plant Alpha',
    location: 'Plant A - Cell 03',
    department: 'Heavy Stamping',
    status: 'Warning',
    runningHours: 2150,
    healthScore: 74,
    temperature: 68.2,
    vibration: 4.82,
    vibrationX: 3.8,
    vibrationY: 4.1,
    vibrationZ: 4.9,
    pressure: 6.2,
    voltage: 412,
    current: 16.2,
    rpm: 1450,
    power: 8.2,
    humidity: 52,
    sensorId: 'SN-SENS-8892',
    operator: 'Elena Rostova',
    lastMaintenance: '2026-05-10',
    nextMaintenance: '2026-08-10',
  },
  {
    machineId: 'MCH-103',
    name: 'Primary Cooling Tower Turbine',
    plant: 'Plant Beta',
    location: 'Plant B - Utility Bay',
    department: 'Plant Utilities',
    status: 'Critical',
    runningHours: 3890,
    healthScore: 48,
    temperature: 84.4,
    vibration: 7.15,
    vibrationX: 6.2,
    vibrationY: 6.8,
    vibrationZ: 7.5,
    pressure: 3.2,
    voltage: 418,
    current: 17.5,
    rpm: 1800,
    power: 9.1,
    humidity: 65,
    sensorId: 'SN-SENS-8893',
    operator: 'David Chen',
    lastMaintenance: '2026-03-22',
    nextMaintenance: '2026-07-30',
  },
  {
    machineId: 'MCH-104',
    name: 'Rotary Screw Compressor B',
    plant: 'Plant Alpha',
    location: 'Plant A - Compressor House',
    department: 'Pneumatics',
    status: 'Healthy',
    runningHours: 1890,
    healthScore: 95,
    temperature: 45.1,
    vibration: 1.88,
    vibrationX: 1.4,
    vibrationY: 1.6,
    vibrationZ: 1.9,
    pressure: 5.5,
    voltage: 414,
    current: 11.2,
    rpm: 1680,
    power: 4.9,
    humidity: 42,
    sensorId: 'SN-SENS-8894',
    operator: 'Sarah Jenkins',
    lastMaintenance: '2026-07-01',
    nextMaintenance: '2026-10-01',
  },
  {
    machineId: 'MCH-105',
    name: 'Automated Robotic Arm 04',
    plant: 'Assembly Plant 1',
    location: 'Assembly Line 02',
    department: 'Robotics',
    status: 'Healthy',
    runningHours: 940,
    healthScore: 99,
    temperature: 38.9,
    vibration: 0.92,
    vibrationX: 0.7,
    vibrationY: 0.8,
    vibrationZ: 0.9,
    pressure: 4.1,
    voltage: 415,
    current: 8.4,
    rpm: 1600,
    power: 3.5,
    humidity: 38,
    sensorId: 'SN-SENS-8895',
    operator: 'Automated',
    lastMaintenance: '2026-07-12',
    nextMaintenance: '2026-10-12',
  },
  {
    machineId: 'MCH-106',
    name: 'Heavy Duty Induction Motor',
    plant: 'Plant Beta',
    location: 'Plant B - Substation',
    department: 'Power Generation',
    status: 'Warning',
    runningHours: 4120,
    healthScore: 68,
    temperature: 71.0,
    vibration: 5.12,
    vibrationX: 4.2,
    vibrationY: 4.8,
    vibrationZ: 5.3,
    pressure: 4.9,
    voltage: 410,
    current: 15.8,
    rpm: 1720,
    power: 7.4,
    humidity: 48,
    sensorId: 'SN-SENS-8896',
    operator: 'Klaus Lindner',
    lastMaintenance: '2026-04-18',
    nextMaintenance: '2026-08-18',
  },
];

module.exports = sampleMachines;
